#Module 5 Assignment — Public Housing Inspections Star Schema
create database module3assignment;

use module3assignment;

select * from public_housing_inspection_data;

WITH FormattedData AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS
    FROM public_housing_inspection_data
    WHERE STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') IS NOT NULL
),
RankedData AS (
    SELECT 
        PHA_NAME,
        INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS,
        LAG(INSPECTION_DATE) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST,
        ROW_NUMBER() OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS RN
    FROM FormattedData
)
SELECT *
FROM RankedData
ORDER BY PHA_NAME, INSPECTION_DATE DESC;

WITH FormattedData AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS
    FROM public_housing_inspection_data
    WHERE STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') IS NOT NULL
),
RankedData AS (
    SELECT 
        PHA_NAME,
        INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS,
        LAG(INSPECTION_DATE) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST
    FROM FormattedData
),
FilteredData AS (
    SELECT 
        PHA_NAME,
        INSPECTION_DATE AS MR_INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
        SECOND_MR_INSPECTION_DATE,
        SECOND_MR_INSPECTION_COST,
        (COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
        ((COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST
    FROM RankedData
    WHERE SECOND_MR_INSPECTION_COST IS NOT NULL
      AND COST_OF_INSPECTION_IN_DOLLARS > SECOND_MR_INSPECTION_COST
)
SELECT *
FROM FilteredData;

WITH FormattedData AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS
    FROM public_housing_inspection_data
    WHERE STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') IS NOT NULL
),
RankedData AS (
    SELECT 
        PHA_NAME,
        INSPECTION_DATE AS MR_INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
        LAG(INSPECTION_DATE) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST
    FROM FormattedData
),
FilteredData AS (
    SELECT 
        PHA_NAME,
        MR_INSPECTION_DATE,
        MR_INSPECTION_COST,
        SECOND_MR_INSPECTION_DATE,
        SECOND_MR_INSPECTION_COST,
        (MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
        ((MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST,
        ROW_NUMBER() OVER (PARTITION BY PHA_NAME ORDER BY MR_INSPECTION_DATE DESC) AS RN
    FROM RankedData
    WHERE SECOND_MR_INSPECTION_COST IS NOT NULL
      AND MR_INSPECTION_COST > SECOND_MR_INSPECTION_COST
)
SELECT 
    PHA_NAME,
    MR_INSPECTION_DATE,
    MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    CHANGE_IN_COST,
    PERCENT_CHANGE_IN_COST
FROM FilteredData
WHERE RN = 1
ORDER BY PHA_NAME;

#References: https://learnsql.com/blog/lead-and-lag-functions-in-sql/
#References: https://stackoverflow.com/questions/26864930/how-to-use-lead-and-lag-in-where